### ISSUE TITLE
The following svg is not visible on Android

### ISSUE THREAD

**Issue by MaxNoack** [software-mansion/react-native-svg#1543] opened 2021-02-23 16:52 UTC
The following Svg is not visible on Android. Works fine on iOS. Adding `fill="black"` to path tag helps but should work without imo.

```bash
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Capa_1" x="0px" y="0px" viewBox="0 0 480 480" style="enable-background:new 0 0 480 480;" xml:space="preserve">
    <path d="M474.608,80.439l-232-80c-1.69-0.583-3.526-0.583-5.216,0l-232,80C2.166,81.551,0.001,84.587,0,87.999v384    c0,4.418,3.582,8,8,8h40c4.418,0,8-3.582,8-8v-248h368v248c0,4.418,3.582,8,8,8h40c4.418,0,8-3.582,8-8v-384    C479.999,84.587,477.834,81.551,474.608,80.439z M40,215.999v248H16v-304h24V215.999z M424,207.999H56v-16h368V207.999z     M424,175.999H56v-16h368V175.999z M464,463.999h-24v-304h24V463.999z M464,143.999H16V93.703l224-77.24l224,77.24V143.999z"/>
</svg>
```
SVG Library Version: 12.1.0
RN Version: 0.63.4

**Comment by ChaossAdept7** [comment] 2021-03-02 15:08
Having similar problem! Thanks for fill="black" option. It helps!

**Comment by sherriff93** [comment] 2021-03-25 11:44
Thanks @MaxNoack, `fill="black"` solved the issue!

This issue also means that Android doesn't render the markerEnd svg on the arrow in the example here: https://github.com/react-native-svg/react-native-svg#marker

If any maintainers want to reproduce, create a blank react native project and paste the code in the above link into `App.js`. The arrowhead won't load.

(Thought it might be useful to post my own (related) problem here for search engines, as it took me a while to get here...)

![image](https://user-images.githubusercontent.com/8101171/112467879-7dfbde00-8d5f-11eb-8a9c-09c1f41c94b1.png)

**Comment by Ethan-G** [comment] 2021-08-10 05:25
For bug impacts/prioritisation: I also encountered this today. Thanks for the workaround though!

**Comment by WoLewicki** [comment] 2022-12-20 16:59
Can you check if applying https://github.com/software-mansion/react-native-svg/pull/1947 fixes your issue?

**Comment by WoLewicki** [comment] 2023-01-03 20:15
Closing since #1947 has been merged. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2023-01-03 20:15 UTC
