### ISSUE TITLE
Error while updating property 'bbWidth' of a view managed by: RNSVGSvgView. Value for bbWidth cannot be cast from Double to String.

### ISSUE THREAD

**Issue by yairopro** [software-mansion/react-native-svg#964] opened 2019-03-10 16:47 UTC
react-native-svg: 9.2.4
react-native: ^0.57.5

![Screenshot_1552236254](https://user-images.githubusercontent.com/8110568/54088250-bee54d80-4364-11e9-8459-268046f10882.png)

**Comment by msand** [comment] 2019-03-10 17:33
Can you provide a reproduction?

**Comment by yairopro** [comment] 2019-03-12 19:56
I don't know how the problem disappeared. I can't reproduce it.
I close the issue.

**Comment by rajatdhoot123** [comment] 2019-05-06 06:33
Same issue is happening with me
![Screenshot 2019-05-06 at 12 01 52 PM](https://user-images.githubusercontent.com/18528826/57209651-e2d8ae80-6ff6-11e9-9749-1ed34c3c97fa.png)

**Comment by pilot4u** [comment] 2019-06-25 22:19
I have same issue with different prop "rx"
![image](https://user-images.githubusercontent.com/28202403/60137702-6b322f00-97b0-11e9-91c4-88b4597ba780.png)

**Comment by yairopro** [comment] 2019-06-26 08:20
Hi @pilot4u
Do you want me to reopen this issue ? I closed it because I could not reproduce it.

> Can you provide a reproduction?

If you manage to tell the steps needed to reproduce this issue, or making a snack about it, I will gladly reopen.

**Comment by pilot4u** [comment] 2019-06-26 11:23
@yairopro After recompiling the native part this issue was resolved.
It took me some time to find this solution, probably there were incompatibility between the native part and the js part.
Therefore I think we shouldn't reopen this issue, but leave this here for future developers who will come across the same issue

**Comment by yairopro** [comment] 2019-06-27 11:58
Yes I agree.
And I'm happy you solved it too.😁

**Comment by jordyvandomselaar** [comment] 2019-08-22 21:59
Running into it as well when using Expo =(

**Comment by harveyconnor** [comment] 2020-09-27 15:04
any solution?

**Comment by majirosstefan** [comment] 2021-07-14 11:48
Still present, in React Native 0.64.1  with: 

"react-native-svg": "^12.1.1",
"react-native-svg-transformer": "^0.14.3",

**Comment by JoshuaJoness** [comment] 2021-11-19 02:36
Also still experiencing.

**Comment by michang05** [comment] 2021-12-09 07:23
> @yairopro After recompiling the native part this issue was resolved. It took me some time to find this solution, probably there were incompatibility between the native part and the js part. Therefore I think we shouldn't reopen this issue, but leave this here for future developers who will come across the same issue

what native part effort did you make?

**Comment by pfreire013** [comment] 2022-01-08 16:43
Hey guys

I was with the similar issue like you can see on the printscreen. I my case the reason of the problem was because when i set the value of width in my svg component I pass the string "auto", but the library react-native-svg could not interpreted this. So I just change the "auto" for "100%" and work it! 

![Screenshot 2022-01-08 at 16 43 03](https://user-images.githubusercontent.com/33518714/148652348-9947584e-7946-4318-9b03-bae7bf2fc1f5.png)
![Screenshot 2022-01-08 at 16 43 12](https://user-images.githubusercontent.com/33518714/148652357-dee8b462-79ea-4016-a47d-61f89500cbfc.png)


In you case I imagine in some where in your code you was passing a double (like 4.50 or 10,5, something like that) value for the width of your svg component. I know it is a little bit boring search the code to find this but works for me and I hope work for you! 

<img width="372" alt="Screenshot 2022-01-08 at 16 34 08" src="https://user-images.githubusercontent.com/33518714/148652138-912186fb-ab8c-416a-acf7-abaa87ce8121.png">

**Comment by WoLewicki** [comment] 2022-08-01 10:15
Can we close this issue then? Seems like the problems are not related to the library itself.

**Comment by majirosstefan** [comment] 2022-08-01 10:20
@WoLewicki Could it be possible to improve error description a little bit, please ?  
Or add some section into Readme about it (at least) ? 

If we would close this without doing anything, people would still spent time looking for solutions, browsing through bugs here & Googling what is going on.

**Comment by WoLewicki** [comment] 2022-08-01 10:33
@majirosstefan do you mean passing the `auto` as the value of a prop?

**Comment by majirosstefan** [comment] 2022-08-01 11:04
No, I meant props validation in general. If the library would receive either malformed props or props that it could not handle, there could be more "dev-friendly" error displayed in the console

**Closed** 2024-10-02 11:35 UTC
Labels: Question, Missing repro
