### ISSUE TITLE
Build issue in React Native new architecture ios.

### ISSUE THREAD

**Issue by neeteshraj** [software-mansion/react-native-svg#2067] opened 2023-06-15 14:38 UTC
I am getting this issue when compiling in newarchitecture. 

The following build commands failed:
	CompileC /Users/niteshrajkhanal/Library/Developer/Xcode/DerivedData/mblconnect-ezjukoxmfjyxlsdktsezjmflqzun/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGUse.o /Users/niteshrajkhanal/Desktop/amnil-intranet-app-mbl/mblconnect/node_modules/react-native-svg/apple/Elements/RNSVGUse.mm normal arm64 objective-c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNSVG' from project 'Pods')
(1 failure)

This is my react-native version 
 "react-native": "0.71.8",
and this is the react-native-svg version that i have installed.
 "react-native-svg": "^13.9.0",

The issue only occurs in new architecture. else it is compiling

**Comment by dev-fredericfox** [comment] 2023-06-17 10:22
Yep, same!

**Comment by nikitapilgrim** [comment] 2023-06-30 06:18
same

**Comment by khanakia** [comment] 2023-07-05 07:48
I belive this is the actual error it throws after upgrading
Showing All Errors Only
/ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/conversions.h:111:39: 'value' is unavailable: introduced in iOS 12.0

**Comment by neeteshraj** [comment] 2023-07-06 01:22
> I belive this is the actual error it throws after upgrading Showing All Errors Only /ios/Pods/Headers/Public/React-Fabric/react/renderer/components/view/conversions.h:111:39: 'value' is unavailable: introduced in iOS 12.0

Any fixes?

**Comment by khanakia** [comment] 2023-07-06 03:06
For now you can fix it by changing the deployment target manually as shown below screenshot
![Screenshot 2023-07-06 at 8 35 56 AM](https://github.com/software-mansion/react-native-svg/assets/2174170/956e6942-9e62-46f5-b7c4-29186772a890)

**Comment by WoLewicki** [comment] 2023-07-07 13:59
Can you check if it still occurs in RN 0.72 and v13.10.0 version of this library?

**Comment by neeteshraj** [comment] 2023-07-08 05:26
> 

It is still persisting in new architecture. i Upgraded to latest version of react-native-version@13.10.0. i am still getting this issue The following build commands failed:
	CompileC /Users/niteshrajkhanal/Library/Developer/Xcode/DerivedData/mblconnect-ezjukoxmfjyxlsdktsezjmflqzun/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/RNSVG.build/Objects-normal/arm64/RNSVGImageShadowNode.o /Users/niteshrajkhanal/Desktop/amnil-intranet-app-mbl/mblconnect/node_modules/react-native-svg/common/cpp/react/renderer/components/rnsvg/RNSVGImageShadowNode.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'RNSVG' from project 'Pods')
(1 failure)
]

Node.js v18.12.0
 and this is my package.json {
  "name": "mblconnect",
  "version": "0.0.1",
  "private": true,
  "reactNativePermissionsIOS": [
    "Calendars",
    "Camera",
    "Contacts",
    "FaceID",
    "LocationAccuracy",
    "LocationAlways",
    "LocationWhenInUse",
    "MediaLibrary",
    "Motion",
    "Notifications",
    "PhotoLibrary",
    "PhotoLibraryAddOnly",
    "Reminders"
  ],
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "ios-14": "npx react-native run-ios --simulator='iPhone 14 Pro'",
    "start": "react-native start",
    "test": "jest --config=/Users/niteshrajkhanal/Desktop/mblintranet/jest.config.js",
    "watch": "jest --watchAll",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "lint:fix": "eslint . --ext .js,.jsx,.ts,.tsx --fix",
    "reverse": "adb reverse tcp:8081 tcp:8081",
    "bundle-android": "react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle",
    "release-android": "cd android && ./gradlew clean && cd .. && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle && cd android && ./gradlew assembleRelease && cd ..",
    "adb-log": "adb logcat *:E",
    "prepare": "husky install",
    "type-check": "tsc",
    "test:report": "jest --collectCoverage --coverageDirectory=\"./coverage\" --ci --reporters=default --reporters=jest-junit --coverage",
    "pod-install": "cd ios && RCT_NEW_ARCH_ENABLED=1 bundle exec pod install && cd ..",
    "postinstall": "react-native setup-ios-permissions && pod-install"
  },
  "dependencies": {
    "@okta/okta-react-native": "^2.8.0",
    "@react-native-async-storage/async-storage": "^1.18.1",
    "@react-native-community/blur": "^4.3.2",
    "@react-native-community/datetimepicker": "^7.1.0",
    "@react-native-community/netinfo": "^9.3.10",
    "@react-native-cookies/cookies": "^6.2.1",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.7",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-bottom-tabs": "^6.2.15",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@react-navigation/stack": "^6.3.16",
    "@reduxjs/toolkit": "^1.9.5",
    "@rneui/base": "^4.0.0-rc.7",
    "@rneui/themed": "^4.0.0-rc.7",
    "axios": "^1.4.0",
    "base64-js": "^1.5.1",
    "bikram-sambat-js": "^1.0.1",
    "d3-shape": "^3.2.0",
    "formik": "^2.4.0",
    "hoist-non-react-statics": "^3.3.2",
    "html-to-text": "^9.0.5",
    "i18next": "^22.5.0",
    "loadsh": "^0.0.4",
    "lottie-react-native": "^5.1.6",
    "memoize-one": "^6.0.0",
    "moment": "^2.29.4",
    "native-base": "^3.4.28",
    "oidc-client": "^1.11.5",
    "prop-types": "^15.8.1",
    "qs": "^6.11.2",
    "react": "18.2.0",
    "react-i18next": "^12.3.1",
    "react-native": "0.72.0",
    "react-native-animatable": "^1.3.3",
    "react-native-app-auth": "^6.4.3",
    "react-native-autoheight-webview": "^1.6.5",
    "react-native-calendars": "^1.1298.0",
    "react-native-crypto-js": "^1.0.0",
    "react-native-document-picker": "^9.0.1",
    "react-native-dropdown-picker": "^5.4.6",
    "react-native-fast-image": "^8.6.3",
    "react-native-flipper": "^0.191.0",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keychain": "^8.1.1",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-mmkv": "^2.10.1",
    "react-native-navigation-bar-color": "^2.0.2",
    "react-native-network-info": "^5.2.1",
    "react-native-onboarding-swiper": "^1.2.0",
    "react-native-paper": "^5.8.0",
    "react-native-permissions": "^3.8.3",
    "react-native-reanimated": "^3.3.0",
    "react-native-reanimated-carousel": "^3.3.2",
    "react-native-redash": "^18.1.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",
    "react-native-skeleton-placeholder": "^5.2.4",
    "react-native-svg": "^13.10.0",
    "react-native-swipe-gestures-plus": "^1.1.3",
    "react-native-toast-message": "^2.1.6",
    "react-native-vector-icons": "^9.2.0",
    "react-navigation-tabbar-collection": "^1.0.0",
    "react-redux": "^8.0.5",
    "recyclerlistview": "^4.2.0",
    "redux-persist": "^6.0.0",
    "rn-fetch-blob": "^0.12.0",
    "uuid": "^9.0.0",
    "xdate": "^0.8.2",
    "yup": "^1.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.0",
    "@react-native/metro-config": "^0.72.6",
    "@react-navigation/devtools": "^6.0.18",
    "@testing-library/jest-native": "^5.4.2",
    "@testing-library/react-native": "^12.1.2",
    "@tsconfig/docusaurus": "^2.0.0",
    "@tsconfig/react-native": "^3.0.0",
    "@types/d3-shape": "^3.1.1",
    "@types/html-to-text": "^9.0.1",
    "@types/jest": "^29.5.2",
    "@types/lodash": "^4.14.195",
    "@types/metro-config": "^0.76.3",
    "@types/qs": "^6.9.7",
    "@types/react": "^18.0.24",
    "@types/react-native": "^0.72.2",
    "@types/react-native-crypto-js": "^1.0.0",
    "@types/react-native-vector-icons": "^6.4.13",
    "@types/react-test-renderer": "^18.0.0",
    "@types/uuid": "^9.0.1",
    "@types/xdate": "^0.8.32",
    "@welldone-software/why-did-you-render": "^7.0.1",
    "babel-jest": "^29.2.1",
    "babel-plugin-inline-dotenv": "^1.7.0",
    "babel-plugin-module-resolver": "^5.0.0",
    "babel-plugin-root-import": "^6.6.0",
    "dotenv": "^16.0.3",
    "eslint": "^8.19.0",
    "husky": "^8.0.3",
    "jest": "^29.5.0",
    "metro-react-native-babel-preset": "0.76.5",
    "prettier": "^2.4.1",
    "react-component-driver": "^0.11.0",
    "react-native-logs": "^5.0.1",
    "react-recipes": "^1.5.0",
    "react-test-renderer": "18.2.0",
    "reassure": "^0.9.1",
    "redux-flipper": "^2.0.2",
    "semver": "^7.5.3",
    "shell-utils": "^1.0.10",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}

**Comment by Dat-Mobile** [comment] 2023-07-08 16:48
> Can you check if it still occurs in RN 0.72 and v13.10.0 version of this library?

I can confirm that it's working now, thanks a lot. The versions below

```
"react-native": "0.72.1",
"react-native-svg": "^13.10.0",
```

**Comment by neeteshraj** [comment] 2023-07-08 17:19
> > Can you check if it still occurs in RN 0.72 and v13.10.0 version of this library?
> 
> I can confirm that it's working now, thanks a lot. The versions below
> 
> ```
> "react-native": "0.72.1",
> "react-native-svg": "^13.10.0",
> ```

Is it working with fabric enabled in ios?

**Comment by Dat-Mobile** [comment] 2023-07-09 03:50
> Is it working with fabric enabled in ios?

Yes sure
`{"fabric":true,"initialProps":{"concurrentRoot":true},"rootTag":1}`

**Comment by WoLewicki** [comment] 2023-07-10 14:35
Since it has been fixed upstream (https://github.com/facebook/react-native/commit/0010c3807d7e47d7d518667dbfac62f7c0da1ac1), you should probably just clear all the cache and reinstall your node_modules to make it work. There is nothing I can do from the library's point of view so I'll close it. Feel free to comment if there is something wrong and we can always reopen it then.

**Closed by WoLewicki** 2023-07-10 14:35 UTC
