### ISSUE TITLE
SVGs that use linearGradient fail to render at all

### ISSUE THREAD

**Issue by gilbertVirgo** [software-mansion/react-native-svg#1348] opened 2020-04-16 11:09 UTC
# SVGs that use linearGradient fail to render at all

Running from an expo app. Using `"react-native-svg": "^12.1.0"` and `"react-native-svg-transformer": "^0.14.3"`.

Other SVGs work fine, and if you change fill to black, the SVG renders as expected (though without the gradient).

### To reproduce...

```bash
expo init app
cd app
npm i && npm i react-native-svg && npm i react-native-svg-transformer
# add below example to project
expo start
```

### App.js
```javascript
// ...
import {SvgXml} from "react-native-svg"

const xml = `<svg width="32" height="32" viewBox="0 0 32 32">
<path
  fill-rule="evenodd"
  clip-rule="evenodd"
  fill="url(#gradient)"
  d="M4 0C1.79086 0 0 1.79086 0 4V28C0 30.2091 1.79086 32 4 32H28C30.2091 32 32 30.2091 32 28V4C32 1.79086 30.2091 0 28 0H4ZM17 6C17 5.44772 17.4477 5 18 5H20C20.5523 5 21 5.44772 21 6V25C21 25.5523 20.5523 26 20 26H18C17.4477 26 17 25.5523 17 25V6ZM12 11C11.4477 11 11 11.4477 11 12V25C11 25.5523 11.4477 26 12 26H14C14.5523 26 15 25.5523 15 25V12C15 11.4477 14.5523 11 14 11H12ZM6 18C5.44772 18 5 18.4477 5 19V25C5 25.5523 5.44772 26 6 26H8C8.55228 26 9 25.5523 9 25V19C9 18.4477 8.55228 18 8 18H6ZM24 14C23.4477 14 23 14.4477 23 15V25C23 25.5523 23.4477 26 24 26H26C26.5523 26 27 25.5523 27 25V15C27 14.4477 26.5523 14 26 14H24Z"
/>
<defs>
  <linearGradient
	id="gradient"
	x1="0"
	y1="0"
	x2="8.46631"
	y2="37.3364"
	gradient-units="userSpaceOnUse">
	<stop offset="0" stop-color="#FEA267" />
	<stop offset="1" stop-color="#E75A4C" />
  </linearGradient>
</defs>
</svg>
`;

// ...
return <SvgXml xml={xml} width="32" height="32"/>
// ...
```

**Comment by gabrielste1n** [comment] 2020-05-09 09:09
I am having the same issue,  it works perfectly on Android but is not showing up at all on ios.

`<Svg
            style={{ position: "absolute", top: 20, left: 15 }}
            width="263.867"
            height="26.596"
            viewBox="0 0 263.867 26.596"
          >
            <Defs>
              <LinearGradient
                id="a"
                x1="0.417"
                y1="-1.542"
                x2="0.637"
                y2="1.842"
                gradientUnits="objectBoundingBox"
              >
                <Stop offset="0" stopColor="#da0c1a" />
                <Stop offset="1" stopColor="#f8810a" />
              </LinearGradient>
            </Defs>
            <Path
              fill="url(#a)"
              class="a"
              d="M1506.542,61.334h7.028L1520.1,76.15l6.5-14.816h6.991v26.6h-6.156V71.781l-5.357,12.766H1517.9l-5.357-12.766V87.93h-6ZM1545,79.266l-8.587-17.932h6.839l4.94,11.549,4.9-11.549h6.764L1551.3,79.266V87.93H1545Zm23.485-17.932h6.421l3.535,18.768,4.558-18.768h5.7l4.56,18.768,3.533-18.768h6.155l-6.421,26.6h-6.573l-4.1-16.909L1581.7,87.93h-6.84Zm36.594,21.352V66.576c0-3.57,1.71-5.242,5.243-5.242h10.221c3.571,0,5.243,1.672,5.243,5.242v16.11c0,3.533-1.672,5.244-5.243,5.244h-10.221C1606.785,87.93,1605.075,86.219,1605.075,82.686Zm13.678-.227c.57,0,.722-.191.722-.723V67.525c0-.568-.152-.72-.722-.72H1612.1c-.532,0-.722.152-.722.72V81.736c0,.532.19.723.722.723Zm32.869,5.471h-6.573l-4.445-9.157h-3.686V87.93h-6.307v-26.6h14.818c3.533,0,5.243,1.672,5.243,5.242v6.649c0,3-1.178,4.636-3.648,5.091Zm-7.978-14.4c.531,0,.721-.152.721-.722V67.412c0-.57-.19-.723-.721-.723h-6.726v6.84Zm27.245,14.4-5.4-10.944-3.875,5.092V87.93h-6.193v-26.6h6.193V73.605l8.587-12.271h7.105l-7.828,10.334,8.246,16.262Zm8.172-5.244V66.576c0-3.57,1.71-5.242,5.243-5.242h10.22c3.572,0,5.244,1.672,5.244,5.242v16.11c0,3.533-1.672,5.244-5.244,5.244H1684.3C1680.771,87.93,1679.061,86.219,1679.061,82.686Zm13.678-.227c.57,0,.722-.191.722-.723V67.525c0-.568-.152-.72-.722-.72h-6.649c-.532,0-.722.152-.722.72V81.736c0,.532.19.723.722.723Zm11.668.227V61.334h6.307V81.623a.629.629,0,0,0,.722.721h6.193c.532,0,.722-.229.722-.721V61.334h6.307V82.686c0,3.457-1.748,5.244-5.243,5.244h-9.765C1706.192,87.93,1704.407,86.143,1704.407,82.686Zm30.475-15.844h-6.915V61.334h20.175v5.508h-6.953V87.93h-6.307Zm15.543,15.844V79.191h6.23v2.7c0,.531.191.72.722.72h6c.531,0,.722-.189.722-.72V79.115c0-.609-.266-.8-1.064-.988l-7.067-1.711c-3.534-.873-5.472-1.861-5.472-5.471V66.576c0-3.57,1.71-5.242,5.244-5.242h8.966c3.534,0,5.243,1.672,5.243,5.242v3.192h-6.23V67.375c0-.57-.191-.723-.722-.723h-5.472c-.532,0-.721.153-.721.723v2.469c0,.607.227.8,1.063.988l7.067,1.709c3.534.875,5.471,1.861,5.471,5.471v4.674c0,3.533-1.709,5.244-5.243,5.244h-9.5C1752.134,87.93,1750.425,86.219,1750.425,82.686Z"
              transform="translate(-1506.542 -61.334)"
            />
          </Svg>`

**Comment by anion155** [comment] 2020-09-25 19:40
Does not work for me too

**Comment by aanah0** [comment] 2020-10-27 10:03
+1
Have an issue at this link
https://identity.moneyhub.co.uk/bank-icons/amex

**Comment by jpalmr** [comment] 2021-02-25 01:45
This issue may be caused by the bitwise operations in [extractGradient.ts L82](https://github.com/react-native-svg/react-native-svg/blob/b2e2c355204ff4b10973d3afce1495f7e4167ff7/src/lib/extract/extractGradient.ts#L82)

As an example,

`0xff << 24` is `-0x1000000`, instead of the expected `0xff000000`

`0x00ffffff | 0xff000000` is `-1`, instead of the expected `0xffffffff`

This line could be rewritten to include `>>> 0` at the end to treat the color as unsigned.

**Comment by zhiqingchen** [comment] 2022-10-26 04:07
Having the same issue on iOS and Android.

**Comment by mohitarora777** [comment] 2022-12-03 17:47
Having issue on IOS , In android works fine

**Comment by WoLewicki** [comment] 2022-12-21 22:13
I tested your the examples provided here on the newest main and did not spot any problems. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-12-21 22:13 UTC
