### ISSUE TITLE
Svg file with mask not working

### ISSUE THREAD

**Issue by jenskuhrjorgensen** [software-mansion/react-native-svg#1377] opened 2020-05-12 09:36 UTC
## Behaviour
Svg files including masks are rendered in low quality/pixelated. The following screenshot includes an svg with and without masks:
![screenshot](https://user-images.githubusercontent.com/28528363/81665414-f6f09080-9440-11ea-8fbf-7faafacd180d.png)

## Expected behaviour
It is expected that the library can render all valid svg's. Putting the XML content of `SvgWithMask.svg` (see [example project](https://github.com/jenskuhrjorgensen/svg-mask-error)) into [this online svg renderer](https://www.rapidtables.com/web/tools/svg-viewer-editor.html) looks fine, but rendering it using `react-native-svg` looks pixelated. 

## Environment info
React native info output:

```bash
System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 386.13 MB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
    Watchman: Not Found
  Managers:
    CocoaPods: 1.8.4 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
    Android SDK:
      API Levels: 19, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.3, 27.0.3, 28.0.0, 28.0.0, 28.0.2, 28.0.3, 29.0.2
      System Images: android-19 | Google APIs ARM EABI v7a, android-19 | Google APIs Intel x86 Atom, android-25 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.4.1/11E503a - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_172 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0
    react-native: 0.62.2 => 0.62.2
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.0

## Steps To Reproduce
An example project with the bug can be found [here](https://github.com/jenskuhrjorgensen/svg-mask-error) and instructions for running the example can be found in the example's README.

**Comment by jenskuhrjorgensen** [comment] 2020-07-11 14:07
Hi @semantic-release-bot 

Please don't close this issue as it is still relevant.

**Comment by jenskuhrjorgensen** [comment] 2020-09-16 08:55
No bot - bad bot!

**Comment by kamwoz** [comment] 2020-10-14 07:34
@jenskuhrjorgensen did you find any solution?

**Comment by kamwoz** [comment] 2020-10-14 07:44
@jenskuhrjorgensen actually solution I found out is to edit SVG file and render all <path>'s directly without any <mask>

**Comment by sheshnathiicmr** [comment] 2020-11-22 10:26
reminding bot not to stale, I am facing the same

**Comment by loveaurell** [comment] 2020-12-03 09:04
I have this issue too, the rendered SVG gets blurry edges if it's using masks

**Comment by beshur** [comment] 2021-03-05 13:15
Same issue.
Nobody has a resolution so far?

**Comment by joebochill** [comment] 2021-07-06 17:42
I too am having the same issue with masks causing a blurred effect. 

As @beshur suggested, increasing the size of the viewbox definition for the SVG works as a temporary workaround. If the svg is used at a size that is ~2-3x the size of the viewbox, you start to notice the blurred edges of the mask.

We have a bunch of svg icons that are defined on a 24px viewbox and it would be nice to not have to update all of their viewboxes in order to use them.

**Comment by WoLewicki** [comment] 2023-01-02 14:43
Since it is a duplicate of #1098, I will close this issue to keep the discussion in one place. You can post your findings there in order to think of proper solutions for the issue. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2023-01-02 14:43 UTC
