### ISSUE TITLE
My SVG file receive error "No Stop in Gradient"

### ISSUE THREAD

**Issue by burhan3759** [software-mansion/react-native-svg#1379] opened 2020-05-13 06:59 UTC
# Question

1. I am not sure this is a bug or i do wrongly
2. https://svgshare.com/i/L5A.svg URL for the svg image

3. I have attached the image here

![Screenshot 2020-05-13 at 2 57 06 PM](https://user-images.githubusercontent.com/9524860/81781065-20d1b200-952a-11ea-9cfe-7054dc1e6a1c.png)

4. How the image should look like

![Screenshot 2020-05-13 at 2 58 38 PM](https://user-images.githubusercontent.com/9524860/81781138-42cb3480-952a-11ea-898e-c5f3ae02f50b.png)

5. Please help solve this issue

**Comment by lukeramsden** [comment] 2020-07-17 14:02
I just got this too from undraw.co's "No data" SVG.

**Comment by FrederickEngelhardt** [comment] 2020-09-01 15:01
In my case I had to scan the file and remove the <LinearGradient /> files that did not contain <stop /> xml elements within them.

**Comment by GardEngen** [comment] 2020-09-04 14:30
@FrederickEngelhardt 
Thanks, that worked for me too 👏

**Comment by ganeshkhedkaraa** [comment] 2021-04-13 06:42
@FrederickEngelhardt ,
Thanks , Its working (y)

**Comment by StefanBlamberg** [comment] 2022-02-17 00:47
We also had issues with undraw svgs looking different, in our case it turned out to be an issue with semi-transparent paths.
Make sure to explicitly add a fill attribute to paths with opacity e.g. `opacity="0.2" fill="#000000"`

**Comment by WoLewicki** [comment] 2022-12-23 11:48
This warning comes from not having any `stop` tags as children of the gradient. It is not a bug in the library, or am I missing something? @StefanBlamberg as for your issue, it should be fixed with #1947. I will close this issue then. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-12-23 11:48 UTC

**Comment by AND-GORNIY** [comment] 2023-02-02 17:07
I resolved this issue uploaded my svg to figma and then reexported variant was with stop tag.
