### ISSUE TITLE
Problem with Circle in 13.7.0

### ISSUE THREAD

**Issue by Splicer97** [software-mansion/react-native-svg#1965] opened 2023-01-16 13:51 UTC
# Bug

The inside of the circle turns black when using version 13.7.0 of the library. There are no problems on 13.6.0 (white color inside Circle).

```
 <SVG viewBox="0 0 15 19" {...rest}>
      <Circle cx="7.5" cy="7.5" r="2.7" stroke={color} strokeWidth="1.6" />
      <Path
        fill-rule="evenodd"
        clip-rule="evenodd"
        d="M0.199951 7.49922C0.199951 4.13876 2.98092 0.199219 7.49995 0.199219C12.019 0.199219 14.8 4.13876 14.8 7.49922C14.8 9.52981 13.8238 11.5855 12.6425 13.3928C11.4504 15.2168 9.97157 16.9016 8.8343 18.1915C8.1336 18.9863 6.87605 19.0241 6.15706 18.1911C5.29522 17.1926 3.82759 15.4089 2.57092 13.4638C1.9426 12.4913 1.35687 11.4629 0.925986 10.4604C0.499429 9.46804 0.199951 8.44521 0.199951 7.49922ZM7.49995 1.79922C4.01898 1.79922 1.79995 4.85968 1.79995 7.49922C1.79995 8.13392 2.008 8.92604 2.39595 9.82858C2.77955 10.721 3.31529 11.6675 3.91485 12.5955C5.11391 14.4515 6.52764 16.1717 7.36826 17.1456C7.42693 17.2136 7.54776 17.2314 7.63415 17.1334C8.77894 15.835 10.183 14.2314 11.3032 12.5175C12.4343 10.7869 13.2 9.0551 13.2 7.49922C13.2 4.85968 10.9809 1.79922 7.49995 1.79922Z"
        fill={color}
      />
    </SVG>
```

If it's still an issue with the latest versions,
please make an sscce in the clean project,
and make it available as a git repo on github.
Or as a https://snack.expo.io/ if expo has the latest version,
and / or the bug exists both in the latest version and the one used in expo and snack.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
System:
    OS: macOS 13.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Memory: 799.99 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - /usr/local/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.5.5 - /usr/local/bin/npm
    Watchman: 2023.01.09.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.17 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.70.6 => 0.70.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 13.7.0

**Comment by Splicer97** [comment] 2023-01-16 13:52
<img width="54" alt="iPhone 14 2023-01-16 16-52-13" src="https://user-images.githubusercontent.com/88652875/212693930-545be174-16d1-438b-b05c-0b4286cd5a6a.png">
All good with 13.6.0 version

**Comment by AndyMeagher** [comment] 2023-01-19 02:55
Also seeing this behavior in 13.7.0

**Comment by PatrickE94** [comment] 2023-01-27 16:43
I added a "missing" fill on my polyline to simply be transparent. I suspect https://github.com/software-mansion/react-native-svg/pull/1947 might have introduced something,  but that's just a guess. Either way, adding `fill="rgba(0,0,0,0)"` solved my issues.

**Comment by Splicer97** [comment] 2023-01-27 19:07
> I added a "missing" fill on my polyline to simply be transparent. I suspect https://github.com/software-mansion/react-native-svg/pull/1947 might have introduced something,  but that's just a guess. Either way, adding `fill="rgba(0,0,0,0)"` solved my issues.

Yeah, it's true, but why black color as default? I think that white color better for this.

**Comment by UNIDY2002** [comment] 2023-01-28 00:49
> Yeah, it's true, but why black color as default? I think that white color better for this. 

According to the specification, black is the default fill color.

https://github.com/software-mansion/react-native-svg/issues/1963

**Comment by Splicer97** [comment] 2023-01-28 13:04
> > Yeah, it's true, but why black color as default? I think that white color better for this. 
> 
> According to the specification, black is the default fill color.
> 
> https://github.com/software-mansion/react-native-svg/issues/1963

Understood, thanks for answer!

**Comment by mkurczewski** [comment] 2023-01-30 15:43
Well, changing the default behavior is a kind of breaking change, but anyway... for me, adding a `fill="none"` property to the `<Svg>` component was enough to fix the icons.

**Comment by WoLewicki** [comment] 2023-01-31 13:17
Since it is a duplicate of #1963, I will close it. If you want to add something to the discussion, please do it there to keep it in one place.

**Closed by WoLewicki** 2023-01-31 13:17 UTC
