### ISSUE TITLE
Svg in Svg

### ISSUE THREAD

**Issue by zotille** [software-mansion/react-native-svg#1495] opened 2020-11-26 03:15 UTC
something like
```
 <Svg>
    <Svg></Svg>
</Svg>
```

display on Web:
![image](https://user-images.githubusercontent.com/38178024/100303857-7ce8b900-2fd8-11eb-9c0d-eaca06744205.png)

display on RN with <SvgCssUri>
![image](https://user-images.githubusercontent.com/38178024/100303958-ae618480-2fd8-11eb-81f2-4f69b365bf10.png)

seems can not display on rn. any one can help?

**Comment by WoLewicki** [comment] 2022-12-21 21:51
Yeah, it seems like a duplicate of #1437 so I will close it to keep the discussion in one place. There is a potential fix provided in that issue. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-12-21 21:51 UTC
