### ISSUE TITLE
the `color` props in `orverride` object of `SvgXml` not working

### ISSUE THREAD

**Issue by chj-damon** [software-mansion/react-native-svg#1616] opened 2021-07-20 09:07 UTC
NB Never post screenshots of code. Post copy paste-able code if you include any.
Ignoring this will likely lead to direct closing of the issue.
Please respect the time and energy of open source maintainers.

# Bug
I'm using svg to render icon in my project, I want to set different color to the icons. for example:
```tsx
const xml = `
<svg t="1626763143756" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1958" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32"><path d="M836.664 302.486c17.528-17.184 45.666-16.906 62.85 0.622 17.184 17.528 16.906 45.666-0.622 62.85L536.226 721.514c-17.53 17.186-45.674 16.906-62.858-0.628L124.924 365.33c-17.18-17.53-16.896-45.67 0.634-62.85 17.532-17.18 45.672-16.896 62.852 0.634L505.74 626.92l330.924-324.434z" p-id="1959" fill="#2c2c2c"></path></svg>
`;

return (
    <SvgXml
      xml={xml}
      override={{
        width: 12,
        height: 12,
        color: 'red',
        ...rest,
      }}
    />
  );
```
the `width` and `height` work perfectly, but `color` doesn't.
I expected the icon color should be red, but actually the color remains `#2c2c2c`.

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

```bash
 // paste it here
System:
    OS: macOS 11.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Memory: 56.68 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
    Watchman: 2021.06.07.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.5 - /usr/bin/javac
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: ^17.0.2 => 17.0.2 
    react-native: 0.63.4 => 0.63.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

Library version: 12.1.1

**Comment by demon3z** [comment] 2021-12-10 02:27
Did you solve it

**Comment by chj-damon** [comment] 2021-12-10 02:30
you can try @td-design/svgicon-cli , I didn't solve this problem but find a way to hack it.

**Comment by demon3z** [comment] 2021-12-10 02:48
I just solved it

**Comment by demon3z** [comment] 2021-12-10 02:55
```
import * as React from 'react';
import { SvgXml } from 'react-native-svg';

const Add = (props: any) => {
    const {fill}= props
    const xml = `
<svg t="1626763143756" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1958" xmlns:xlink="http://www.w3.org/1999/xlink" width="32" height="32">
<path d="M836.664 302.486c17.528-17.184 45.666-16.906 62.85 0.622 17.184 17.528 16.906 45.666-0.622 62.85L536.226 721.514c-17.53 17.186-45.674 16.906-62.858-0.628L124.924 365.33c-17.18-17.53-16.896-45.67 0.634-62.85 17.532-17.18 45.672-16.896 62.852 0.634L505.74 626.92l330.924-324.434z" p-id="1959" fill=${fill}>
</path>
</svg>
`;
    return (
        <SvgXml xml={xml} width={props.width} height={props.height} fill={props.fill} />
    )
};

export default `Add;`
```
  
use: 
```
import AddSvg from 'src/assets/svg/add';
<AddSvg width={50} height={50} fill={'blue'} />
```

the key is :
const {fill}= props
fill=${fill}
you can try this.

**Comment by chj-damon** [comment] 2021-12-10 02:59
yeah, that's the same like what I've done in my tool

**Comment by shoaib039** [comment] 2022-08-18 22:36
I made another better and easy way to fill and stroke color.

**I make a component -> Svg.js**

`import React from "react";
import { Image } from "react-native";
import { SvgXml } from 'react-native-svg';

const Svg = (prop) => {
	
	const { xml, height, width, fill, stroke } = prop;
	
	let dataSource = xml;
	
	if(stroke){
		dataSource = dataSource.replace(/(stroke=")(#[a-f0-9]{1,9})(")/, 'stroke="' + stroke + '"');
	}
	
	if(fill){
		dataSource = dataSource.replace(/(fill=")(#[a-f0-9]{1,9})(")/, 'fill="' + fill + '"');
	}
	
    return (
		<SvgXml width={width} height={height} xml={dataSource} />
    );
	
}

export default Svg;`


**Then in any screen use like this:**

//Component
import Svg from '../components/Svg';

//SVG
import Location from '../../assets/svg/location.svg';

`<Svg width="25" height="25" stroke="#f00" fill="#000" xml={Location} />`

**Comment by WoLewicki** [comment] 2022-12-21 23:48
I believe it is a duplicate of https://github.com/software-mansion/react-native-svg/issues/1317 so I will close it to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-12-21 23:48 UTC
