### ISSUE TITLE
*.metal files in pod dependency

### ISSUE THREAD

**Issue by stephenkopylov** [software-mansion/react-native-svg#2571] opened 2024-12-09 14:00 UTC
### Description

Hi everyone,

Would it make sense to exclude .metal files from the podspec dependencies?

Currently, we already include compiled shaders as .metallib binaries, so is there a specific reason to include the .metal sources as well?

By default, these shader sources are compiled into default.metallib, which can create conflicts with other libraries that also include shader sources (e.g., “multiple commands produce default.metallib”).

Let me know your thoughts!

### Steps to reproduce

Have any other lib with .metal-sources included

### Snack or a link to a repository

-/-

### SVG version

v15.10.1

### React Native version

0.73.1

### Platforms

iOS

### JavaScript runtime

None

### Workflow

None

### Architecture

None

### Build type

None

### Device

iOS simulator

### Acknowledgements

Yes

**Comment by RuudBurger** [comment] 2024-12-11 13:57
The ☝️ mentioned patch file, for people running into similar issues:

```
diff --git a/RNSVG.podspec b/RNSVG.podspec
index b3e0ca3a770254608a75a788148f49e52e8bf581..0d0aafa06f75dcfc93b47337bcd3b0fcb64afb97 100644
--- a/RNSVG.podspec
+++ b/RNSVG.podspec
@@ -12,7 +12,7 @@ Pod::Spec.new do |s|
   s.homepage          = package['homepage']
   s.authors           = 'Horcrux Chen'
   s.source            = { :git => 'https://github.com/react-native-community/react-native-svg.git', :tag => "v#{s.version}" }
-  s.source_files      = 'apple/**/*.{h,m,mm,metal}'
+  s.source_files      = 'apple/**/*.{h,m,mm}'
   s.ios.exclude_files = '**/*.macos.{h,m,mm}'
   s.tvos.exclude_files = '**/*.macos.{h,m,mm}'
   s.visionos.exclude_files = '**/*.macos.{h,m,mm}' if s.respond_to?(:visionos)
```

**Comment by jakex7** [comment] 2024-12-12 08:48
Hi, thank you for bringing this issue to our attention. This is indeed unintended behavior, and `*.metal` files should not be included in `source_files`. This will be fixed in the next version.

**Closed** 2024-12-12 10:49 UTC
Labels: Missing repro
