### ISSUE TITLE
RNSVGImage is not fabric compatible

### ISSUE THREAD

**Issue by kevin-williams** [software-mansion/react-native-svg#1984] opened 2023-02-06 18:27 UTC
# Bug

I'm using images in my SVGs extensively, but upgrading to fabric gives the RNSVGImage is not fabric compatible.

  return (
    <G>
      <Image
        x={x - maxSize / 2}
        y={y - maxSize / 2}
        width={maxSize}
        height={maxSize}
        href={IMAGES[dsoName].img}
        opacity="0.6"
      />
      <Circle r={maxSize * 0.75} fill={dsoFill} cx={x} cy={y} />
    </G>
  );

## Environment info

Run `react-native info` in your terminal and copy the results here. Also, include the *precise* version number of this library that you are using in the project

React native info output:

System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 91.70 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 8.19.3 - /usr/local/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/lib/ruby/gems/3.0.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 27, 28, 29, 30, 31, 32, 33
      Build Tools: 28.0.3, 29.0.2, 30.0.2, 30.0.3, 31.0.0, 32.0.0, 33.0.0, 33.0.1
      System Images: android-29 | ARM 64 v8a, android-30 | Google Play ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-32 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.1 AI-211.7628.21.2111.8092744
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.14.1 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0
    react-native: 0.71.2 => 0.71.2
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

Library version: 13.8.0

## Steps To Reproduce

Issues without reproduction steps or code are likely to stall.

Try and render any SVGImage and it's not been implemented yet.

**Comment by kr-yeon** [comment] 2023-05-03 16:59
+ 1
What is fucking error...
This project is already support fabric!!!

**Comment by kr-yeon** [comment] 2023-05-03 17:11
this is my react-native info

System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M2
    Memory: 5.31 GB / 24.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.10.0/bin/yarn
    npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
    Watchman: 2023.04.10.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.0 - /Users/jeong-yeonho/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9477386
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.6 => 0.71.6 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by kr-yeon** [comment] 2023-05-04 05:42
This is my code
```
<WithLocalSvg
    asset={require('@assets/icons/text/trade_list.svg')}
    width={18}
    height={22}
  />
```

hmm... If you include png in svg, it seems that this error occurs. Could you please confirm that you are using an svg that contains a png inside it?
@kevin-williams

**Comment by mohammadkhizerkhan** [comment] 2023-05-10 07:00
@kr-yeon i'm getting this error when i'm trying this approach
`import * as React from 'react';
import { SvgXml } from 'react-native-svg';

const xml = `
  <svg width="32" height="32" viewBox="0 0 32 32">
    <path
      fill-rule="evenodd"
      clip-rule="evenodd"
      fill="url(#gradient)"
      d="M4 0C1.79086 0 0 1.79086 0 4V28C0 30.2091 1.79086 32 4 32H28C30.2091 32 32 30.2091 32 28V4C32 1.79086 30.2091 0 28 0H4ZM17 6C17 5.44772 17.4477 5 18 5H20C20.5523 5 21 5.44772 21 6V25C21 25.5523 20.5523 26 20 26H18C17.4477 26 17 25.5523 17 25V6ZM12 11C11.4477 11 11 11.4477 11 12V25C11 25.5523 11.4477 26 12 26H14C14.5523 26 15 25.5523 15 25V12C15 11.4477 14.5523 11 14 11H12ZM6 18C5.44772 18 5 18.4477 5 19V25C5 25.5523 5.44772 26 6 26H8C8.55228 26 9 25.5523 9 25V19C9 18.4477 8.55228 18 8 18H6ZM24 14C23.4477 14 23 14.4477 23 15V25C23 25.5523 23.4477 26 24 26H26C26.5523 26 27 25.5523 27 25V15C27 14.4477 26.5523 14 26 14H24Z"
    />
    <defs>
      <linearGradient
        id="gradient"
        x1="0"
        y1="0"
        x2="8.46631"
        y2="37.3364"
        gradient-units="userSpaceOnUse">
        <stop offset="0" stop-color="#FEA267" />
        <stop offset="1" stop-color="#E75A4C" />
      </linearGradient>
    </defs>
  </svg>
`;

export default () => <SvgXml xml={xml} width="100%" height="100%" />;`

**Comment by mohammadkhizerkhan** [comment] 2023-05-10 07:02
@kr-yeon i'm getting this error when i'm trying this approach

```jsx
import * as React from 'react';
import { SvgXml } from 'react-native-svg';

const xml = `
  <svg width="32" height="32" viewBox="0 0 32 32">
    <path
      fill-rule="evenodd"
      clip-rule="evenodd"
      fill="url(#gradient)"
      d="M4 0C1.79086 0 0 1.79086 0 4V28C0 30.2091 1.79086 32 4 32H28C30.2091 32 32 30.2091 32 28V4C32 1.79086 30.2091 0 28 0H4ZM17 6C17 5.44772 17.4477 5 18 5H20C20.5523 5 21 5.44772 21 6V25C21 25.5523 20.5523 26 20 26H18C17.4477 26 17 25.5523 17 25V6ZM12 11C11.4477 11 11 11.4477 11 12V25C11 25.5523 11.4477 26 12 26H14C14.5523 26 15 25.5523 15 25V12C15 11.4477 14.5523 11 14 11H12ZM6 18C5.44772 18 5 18.4477 5 19V25C5 25.5523 5.44772 26 6 26H8C8.55228 26 9 25.5523 9 25V19C9 18.4477 8.55228 18 8 18H6ZM24 14C23.4477 14 23 14.4477 23 15V25C23 25.5523 23.4477 26 24 26H26C26.5523 26 27 25.5523 27 25V15C27 14.4477 26.5523 14 26 14H24Z"
    />
    <defs>
      <linearGradient
        id="gradient"
        x1="0"
        y1="0"
        x2="8.46631"
        y2="37.3364"
        gradient-units="userSpaceOnUse">
        <stop offset="0" stop-color="#FEA267" />
        <stop offset="1" stop-color="#E75A4C" />
      </linearGradient>
    </defs>
  </svg>
`;

export default () => <SvgXml xml={xml} width="100%" height="100%" />;
```

**Comment by kr-yeon** [comment] 2023-05-16 05:29
the react-native last version(0.71.8) is disable newArchitecture. kkkk
can u disable neweArchitecture in gradle.properties?
i think they know that this are not perfect yet.

**Comment by kr-yeon** [comment] 2023-05-16 05:29
How about subtracting the linearGradient from the code above?

**Comment by dev-fredericfox** [comment] 2023-06-05 22:47
Idk it's broken on react-native@next

**Comment by kevin-williams** [comment] 2023-09-21 20:02
> This is my code
> 
> ```
> <WithLocalSvg
>     asset={require('@assets/icons/text/trade_list.svg')}
>     width={18}
>     height={22}
>   />
> ```
> 
> hmm... If u include png in svg, it seems that this error occurs. Could u please confirm that u r using an svg that contains a png inside it? I don't get an error for things that don't have an Image tag inside. Could u check this out and expand on this issue? @kevin-williams

Yes I am using PNG for my render and still get the issue.

**Comment by kevin-williams** [comment] 2023-09-21 21:06
@kr-yeon 
Yeah confirmed it still fails if I use a PNG in my <Image> tag.

I downloaded an SVG file and use that directly instead and I still get the issue on android.  Haven't tested IOS yet.

![Screenshot_1695330259](https://github.com/software-mansion/react-native-svg/assets/11356566/65666658-0a1f-4ad0-af1e-615b3074eab1)

**Comment by kevin-williams** [comment] 2023-09-21 21:19
It works under IOS though!

**Comment by kevin-williams** [comment] 2023-10-19 06:42
I tested again on RN 72.6 (upgraded from 7.24) and now it works on android and ios!

**Comment by WoLewicki** [comment] 2023-10-30 12:09
I will close this issue since all components have been migrated to new arch already :rocket: If you spot any issues, please provide a small repo with reproduction included.

**Closed by WoLewicki** 2023-10-30 12:09 UTC
