### ISSUE TITLE
Accept fill color in SvgUri

### ISSUE THREAD

**Issue by GabrielBrotas** [software-mansion/react-native-svg#1650] opened 2021-09-30 19:18 UTC

**Comment by WoLewicki** [comment] 2022-12-21 23:47
From the issue name, I believe it is a duplicate of https://github.com/software-mansion/react-native-svg/issues/1317 so I close it to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-12-21 23:47 UTC
