### ISSUE TITLE
React Native 0.64

### ISSUE THREAD

**Issue by teamzz111** [software-mansion/react-native-svg#1552] opened 2021-03-13 05:57 UTC
# Feature Request

Support for react native 0.64, 

Metro config:

● Validation Warning:
```
 Unknown option "t" with value {"babelTransformerPath": "/Users/andreslargo/Develop/chamba-app/node_modules/react-native-svg-transformer/index.js", "getTransformOptions": [Function getTransformOptions]} was found.

```

## Why it is needed

App doesn't work on 0.64:

On previus versions works normally.

```
Namespace tags are not supported by default. React's JSX doesn't support namespace tags. You can set `throwIfNamespace: false` to bypass this warning.
> 1 | <svg enable-background="new 0 0 512 512" version="1.1" viewBox="0 0 512 512" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><g id="Layer_1"><circle cx="256" cy="256" fill="#55ACEE" r="238.2"/></g><g id="Layer_2"><g id="Layer_2_1_"><g><path d="M116.3,344.2c31.3,3,59-4.9,84.3-23.8     c-6.6-0.5-12.3-1.4-17.8-3.4c-14.5-5.2-25.3-14.6-32.2-28.2c-1-1.9-1.8-4-2.7-6c-1-2,0-2.4,1.8-2c7.2,1.1,14.2,0.7,21.3-0.8     c0.1,0,0.2-0.2,0.5-0.3c0.1-0.8-0.5-0.9-1-1c-15.9-4-27.9-13.3-36.1-27.4c-4.7-8-7.1-16.6-7.3-25.8c0-2.4,0.6-2.6,2.6-1.7     c7.1,3.4,14.5,5.5,23,5.8c-4.1-3.3-7.9-6.3-10.9-9.9c-11.3-13.3-15.9-28.6-13.7-45.9c0.8-6.5,2.8-12.4,5.7-18.3     c1-2.2,1.8-2.4,3.4-0.5c9.2,11.2,19.9,20.7,31.8,29c8.9,6.3,18.3,11.4,28.2,15.7c12.9,5.6,26.2,9.3,40,11.6     c4.7,0.7,9.3,0.9,13.9,1.5c2.2,0.2,2.5-0.6,2-2.5c-2.3-12-0.8-23.7,4.4-34.6c8.2-17.1,21.6-28,40.3-32     c18.4-3.9,34.8,0.7,49.4,12.4c4.7,7.1,10.6,3,15.9,1.5c8.5-2.4,16.5-6,24.4-10.2c-4,12.9-12,22.7-23,30.4     c10.7-0.7,20.6-4,31.2-8.2c-2.8,4.4-5.7,8-8.5,11.4c-5.4,6.4-11.5,11.8-18.1,16.9c-1.4,1-1.7,2-1.7,3.6     c0.3,11.6-0.6,23.1-2.7,34.5c-2.2,12-5.7,23.5-10.4,34.6c-5.2,12.4-11.8,24.3-19.9,35.1c-10,13.5-21.9,25.4-35.6,35.2     c-18.6,13.2-39.2,21.9-61.5,26.1c-14,2.7-28.1,3.5-42.5,2.8c-11-0.6-21.9-2.3-32.6-5c-13.3-3.4-26.1-8.5-38-15.4     C121.7,347.8,118.8,346.7,116.3,344.2z" fill="none" stroke="#FAFAFA" stroke-miterlimit="10" stroke-width="10"/></g></g></g></svg>```


<img width="476" alt="Captura de Pantalla 2021-03-13 a la(s) 12 56 43 a  m" src="https://user-images.githubusercontent.com/37392536/111020896-fbeedb00-8396-11eb-863d-3fe2ea17ab24.png">

**Comment by WoLewicki** [comment] 2022-03-07 15:48
Can we close this issue? Or is it still valid? If so, could you provide a simple reproduction of the problem?

**Comment by dinhnhanfpt** [comment] 2022-03-09 04:13
iIhave the same issue. any solution for this???

**Comment by WoLewicki** [comment] 2022-03-09 11:58
@dinhnhanfpt can you provide a reproduction of your issue? In the `Validation Warning` there seems to be mentioned [react-native-svg-transformer](https://github.com/kristerkari/react-native-svg-transformer), not `react-native-svg`, so maybe it is an issue from that library?

**Closed** 2024-06-17 08:35 UTC
