### ISSUE TITLE
SvgXml does not use fill='#000' as default

### ISSUE THREAD

**Issue by msageryd** [software-mansion/react-native-svg#1753] opened 2022-04-14 07:32 UTC
RNSVG 12.3.0

# Bug

SVG files which include paths without a fill attribute will not get any fill color unless fill={'#000'} is explicitly applied to the SvgXml component. All other SVG renderers I have tested applies black to such paths, and I think this is a standard behaviour.

The RNSVG docs states that default is #000 for the fill attribute, but this does not seem to apply to SvgXml. I don't know if there are arguments for not applying defaults to xml files. If that's the case I think this should be noted in the docs.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/4483085/163336307-0133145d-150d-4d18-9527-7ff469fa943a.png">

# Workaround

`<SvgXml xml={svgXmlString} width={40} height={40} fill={'#000'} />`

**Comment by WoLewicki** [comment] 2022-12-20 17:01
I think it is a duplicate of https://github.com/software-mansion/react-native-svg/issues/1543 and there is a PR with a potential fix linked there so I will close this issue to keep the discussion in one place. Can you check if applying the PR fixes your issue?

**Closed by WoLewicki** 2022-12-20 17:01 UTC
