### ISSUE TITLE
Error while updating property "d" of a view managed by RNSVGPath (Invalid number formatting character 'N')

### ISSUE THREAD

**Issue by kristianlaw** [software-mansion/react-native-svg#1491] opened 2020-11-19 16:47 UTC
Using a Ring chart and updating the data array with useState. When typing to TextInput it crashes and gives that error.
This only happens when updating it with textinput, if I manually type for example 1 to OHP useState it works as intended.
**Error**
Error while updating property "d" of a view managed by RNSVGPath (Invalid number formatting character 'N')(i=2, s=M NaN NaN A 40 40 0 0 1 NaN NaN L NaN NaN A 40 40 0 0 0 NaN NaN Z)

**Versions**
React-native-svg 12.1.0
React-native ~0.63.3

Any help would be very appreciated

**Code**
` export default function Progress({ route,  navigation }) {
  const [ohp, setOhp] = useState(0); 
  const [bench, setBench] = useState(0); 
  const [squat, setSquat] = useState(0); 

  const data = {
  labels: ["OHP", "Bench", "Squat"], 
  data: [ohp, bench, squat] 
};
<TextInput placeholder='Overheadpress' onChangeText={ohp => setOhp(ohp)}
        value={ohp}/>
`

**Comment by MyRealFood** [comment] 2020-11-19 18:50
Same here!

**Comment by nitzanbueno** [comment] 2020-11-22 21:57
Hey, if this is the same issue you can check out the fix I made [here](https://github.com/nitzanbueno/react-native-svg/commit/b0efde3d4c47a488185460120babcb37d915d412).

**Comment by kristianlaw** [comment] 2020-11-22 22:14
> Hey, if this is the same issue you can check out the fix I made [here](https://github.com/nitzanbueno/react-native-svg/commit/b0efde3d4c47a488185460120babcb37d915d412).
How would you use this?

**Comment by nitzanbueno** [comment] 2020-11-22 22:44
For my project, I used a submodule of the library as a local node module.
However, it'd definitely be nicer if the author could approve/review the PR.

**Comment by jarederaj** [comment] 2021-02-05 19:23
I think you may be triggering this error because your code is attempting to render a path that is outside the bounds of the SVG. An example would be a 30 day graph that has a path attempting to render 31 days.

**Comment by WoLewicki** [comment] 2022-03-08 12:49
Could you provide a minimal reproduction of this issue so we can work on it? Or is it the same issue as https://github.com/react-native-svg/react-native-svg/issues/1418? If so, can we close it?

**Comment by WoLewicki** [comment] 2022-10-11 13:35
Closing due to no response provided. Feel free to comment here with a reproduction and we can always reopen it then.

**Closed by WoLewicki** 2022-10-11 13:35 UTC

**Comment by dexy58** [comment] 2022-10-16 15:18
I have this error:

My chart data looks like this:

[{"x":"2022-10-15T16:00:00Z","y":"17.966884613037"},{"x":"2022-10-15T17:00:00Z","y":"18.260791778564"},{"x":"2022-10-15T18:00:00Z","y":"18.201978683472"},{"x":"2022-10-15T19:00:00Z","y":"18.31120300293"},{"x":"2022-10-15T20:00:00Z","y":"18.294399261475"},{"x":"2022-10-15T21:00:00Z","y":"18.260791778564"},{"x":"2022-10-15T22:00:00Z","y":"18.210350036621"},{"x":"2022-10-15T23:00:00Z","y":"18.143165588379"},{"x":"2022-10-16T00:00:00Z","y":"18.076013565063"},{"x":"2022-10-16T01:00:00Z","y":"17.992057800293"},{"x":"2022-10-16T02:00:00Z","y":"17.908132553101"},{"x":"2022-10-16T03:00:00Z","y":"17.832611083984"},{"x":"2022-10-16T04:00:00Z","y":"17.757118225098"},{"x":"2022-10-16T05:00:00Z","y":"17.690029144287"},{"x":"2022-10-16T06:00:00Z","y":"17.622940063477"},{"x":"2022-10-16T07:00:00Z","y":"17.564283370972"},{"x":"2022-10-16T08:00:00Z","y":"17.513996124268"},{"x":"2022-10-16T09:00:00Z","y":"17.480514526367"},{"x":"2022-10-16T10:00:00Z","y":"17.480514526367"},{"x":"2022-10-16T11:00:00Z","y":"17.497224807739"},{"x":"2022-10-16T12:00:00Z","y":"17.539171218872"},{"x":"2022-10-16T13:00:00Z","y":"17.497224807739"},{"x":"2022-10-16T14:00:00Z","y":"17.706802368164"},{"x":"2022-10-16T15:00:00Z","y":"17.614599227905"},{"x":"2022-10-16T15:11:53.610227805Z","y":"17.91650390625"}]

My component looks like this:

`return (
        <>
            <Chart
                style={styles.chartContainer}
                padding={{ bottom: 20, top: 20, left: 20, right: 20 }}
            >
                <VerticalAxis
                    //tickCount={props.data.length - 1}
                    includeOriginTick={false}
                    theme={{
                        axis: { stroke: { color: "#00BFFF", width: 2 } },
                        ticks: { stroke: { color: "#DCDCDC", width: 2 } },
                        labels: {
                            label: { color: "#21618C" },
                        },
                    }}
                />
                <HorizontalAxis
                    //tickCount={props.data.length - 1}
                    includeOriginTick={false}
                    theme={{
                        axis: { stroke: { color: "#00BFFF", width: 2 } },
                        ticks: { stroke: { color: "#DCDCDC", width: 2 } },
                        labels: {
                            label: { color: "#21618C" },
                        },
                    }}
                />
                <Area
                    data={props.data}
                    smoothing="cubic-spline"
                    theme={{
                        gradient: { from: { color: "#10ac84", opacity: 1 }, to: { color: "#10ac84", opacity: 0.4 } },
                    }}
                />
                <Line
                    data={props.data}
                    smoothing="cubic-spline"
                />
            </Chart>
        </>
    );`

I use these versions:
react-native-svg: 13.4.0
react-native: 0.64.3
react-native-gesture-handler: 2.1.0
react-native-responsive-linechart: 5.7.1

I am getting this error.

**Error while updating property 'd' of a view managed by: RNSVGPath

null

Invalid number formatting character 'N' (i=1 s=MNaN -247.049....)**
