### ISSUE TITLE
is it possible to change svg color using svguri

### ISSUE THREAD

**Issue by kimsean** [software-mansion/react-native-svg#1667] opened 2021-11-24 15:52 UTC
Hi, i would like to ask if its possible to change the svg color using the svguri here is my code

`import { SvgUri } from 'react-native-svg'
<SvgUri
       width="24"
       height="24"
        uri="https://thenewcode.com/assets/images/thumbnails/homer-simpson.svg"
 />`

**Comment by WoLewicki** [comment] 2022-12-21 23:44
I believe it is a duplicate of https://github.com/software-mansion/react-native-svg/issues/1667, so I will close this issue to keep the discussion in one place. Feel free to comment here if something is wrong and we can always reopen it then.

**Closed by WoLewicki** 2022-12-21 23:44 UTC

**Comment by WoLewicki** [comment] 2023-08-01 15:54
Ups 😅 Do you have an idea where should it have lead to?

**Comment by ricbermo** [comment] 2023-08-01 17:12
@WoLewicki probably [this](https://github.com/software-mansion/react-native-svg/issues/1317#issuecomment-861498269)
