### ISSUE TITLE
How to make round border Rect?

### ISSUE THREAD

**Issue by dubiao** [software-mansion/react-native-svg#1725] opened 2022-03-22 08:54 UTC
# Feature Request

I want show a round border rect (with also so said "borderRadius") but I am not able to find a way to make

## Why it is needed

Designers' request

## Possible implementation
```jsx
<Svg width="200" height="60">
  <Rect
    x="25"
    y="5"
    width="150"
    height="50"
    fill="rgb(0,0,255)"
    strokeWidth="3"
    stroke="rgb(0,0,0)"


    **borderRadius**={5}
    **topLeftBorderRadius**={15}
    **bottomRightBorderRadius**={30}


  />
</Svg>
```

**Comment by dubiao** [comment] 2022-03-22 09:00
I found it. use a rx and ry props to get round corners.

but not able to set each corner to different values.

**Comment by WoLewicki** [comment] 2022-03-22 09:22
I believe it is a duplicate of https://github.com/react-native-svg/react-native-svg/issues/1393. Could we close it to keep the discussion in one place?

**Closed** 2024-06-19 07:51 UTC
